# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import testing
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


app = QApplication(sys.argv)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 130, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 190, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 561, 315))
        # self.label_2.setStyleSheet("image : url(:/newPrefix/wallpaper.jpg)")
        self.label_2.setStyleSheet("image : url(./wallpaper1.png)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Pengenalan Kata dalam Bahasa Isyarat Indonesia (BISINDO)", "Pengenalan Kata dalam Bahasa Isyarat Indonesia (BISINDO)"))
        self.pushButton.setText("Mulai")
        self.pushButton.clicked.connect(self.Mulai)
        self.pushButton_2.setText("Keluar")
        self.pushButton_2.clicked.connect(self.Quit)
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">BISINDO</span></p><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">Hand Sign Recognition</span></p></body></html>"))

    def Mulai(self):
        yolo = testing.Yolo()
        yolo.run()
        
    def Quit(self) :
        app.quit()

if __name__ == "__main__" :
    screen = QtWidgets.QMainWindow()
    win = Ui_Dialog()
    win.setupUi(screen)
    screen.show()
    sys.exit(app.exec_())
